FROM node:18.15-alpine as runner
ARG APP
RUN apk add --no-cache dumb-init
ENV NODE_ENV production
EXPOSE 3000
WORKDIR /usr/src/app
COPY dist/storybook/base-ui .
RUN npm i -g serve
CMD [ "serve" ]
